from pathlib import Path
import sys

_THESIS_ROOT = Path(__file__).resolve().parents[2]
_WORKSPACE_SRC = _THESIS_ROOT.parent / "src"
if _WORKSPACE_SRC.exists() and str(_WORKSPACE_SRC) not in sys.path:
    sys.path.insert(0, str(_WORKSPACE_SRC))

from .artifacts import RunArtifactPaths, make_run_artifact_paths, write_manifest
from .data import (
    DatasetBundle,
    RAW_PARQUET_PATH,
    build_dataset_bundle,
    compute_dataset_summary,
    load_dataset_summary,
    load_enriched_dataset,
    load_raw_dataset,
)
from .domain import DomainShiftBundle, get_domain_shift_bundle, infer_feature_group
from .features import (
    CONTEXT_BASE_COLS,
    add_context_features,
    get_acg_columns,
    get_feature_view,
    get_unit_feature_columns,
    get_waveform_columns,
    infer_numeric_feature_columns,
)
from .limitations import LimitationsBundle, get_limitations_bundle, load_leave_one_family_out_summary
from .modeling import (
    ExperimentResult,
    FMISS_RECIPE_GROUPS,
    FPOS_RECIPE_GROUPS,
    MODELING_ROOT,
    RecipeSpec,
    StackSet,
    build_ablation_bundle,
    build_benchmark_table,
    build_family_summary,
    build_recipe_inventory,
    build_recording_summary,
    get_main_benchmark_table,
    get_main_text_recipe_ids,
    get_recipe,
    get_recipe_groups,
    get_recipe_specs,
    get_recipes,
    list_recipes,
    load_experiment,
    load_or_run_experiment,
    load_recipe_result,
    run_experiment,
    run_recipe,
    validate_recipe_registry,
)
from .paths import THESIS_ROOT, get_thesis_root
from .plots import (
    apply_thesis_style,
    bootstrap_r2_significance,
    notebook_output_dirs,
    plot_approach_comparison,
    plot_benchmark_metric,
    plot_domain_auc_annotated,
    plot_domain_shift_separability,
    plot_family_r2_heatmap,
    plot_fpos_fmiss_ladder,
    plot_fpos_shap_top,
    plot_group_metric,
    plot_label_budget,
    plot_pca_projection,
    plot_pca_projection_3d,
    plot_prediction_scatter,
    plot_target_asymmetry,
    plot_top_feature_shift,
    plot_waterfall_progression,
    save_figure,
    save_table,
)
from .protocols import (
    SplitResult,
    build_label_budget_subset,
    leave_one_family_out,
    make_recording_key,
    recording_disjoint_split,
    validate_disjoint_recordings,
)
from .story import (
    build_ablation_winner_table,
    build_benchmark_progress_table,
    build_dataset_partition_table,
    build_extreme_groups_table,
    build_family_coverage_table,
    build_feature_inventory_table,
    build_main_wave_summary,
    build_prediction_diagnostics,
    build_shap_group_summary,
    build_target_missingness_table,
)
from .xai import build_target_asymmetry_table, load_fpos_shap_importance

__all__ = [
    "CONTEXT_BASE_COLS",
    "DatasetBundle",
    "DomainShiftBundle",
    "ExperimentResult",
    "FMISS_RECIPE_GROUPS",
    "FPOS_RECIPE_GROUPS",
    "LimitationsBundle",
    "MODELING_ROOT",
    "RAW_PARQUET_PATH",
    "RecipeSpec",
    "RunArtifactPaths",
    "SplitResult",
    "StackSet",
    "THESIS_ROOT",
    "add_context_features",
    "apply_thesis_style",
    "bootstrap_r2_significance",
    "build_ablation_bundle",
    "build_ablation_winner_table",
    "build_benchmark_progress_table",
    "build_benchmark_table",
    "build_dataset_bundle",
    "build_dataset_partition_table",
    "build_extreme_groups_table",
    "build_family_coverage_table",
    "build_family_summary",
    "build_feature_inventory_table",
    "build_label_budget_subset",
    "build_main_wave_summary",
    "build_prediction_diagnostics",
    "build_recipe_inventory",
    "build_recording_summary",
    "build_shap_group_summary",
    "build_target_asymmetry_table",
    "build_target_missingness_table",
    "compute_dataset_summary",
    "get_acg_columns",
    "get_domain_shift_bundle",
    "get_feature_view",
    "get_limitations_bundle",
    "get_main_benchmark_table",
    "get_main_text_recipe_ids",
    "get_recipe",
    "get_recipe_groups",
    "get_recipe_specs",
    "get_recipes",
    "get_thesis_root",
    "get_unit_feature_columns",
    "get_waveform_columns",
    "infer_feature_group",
    "infer_numeric_feature_columns",
    "leave_one_family_out",
    "list_recipes",
    "load_dataset_summary",
    "load_enriched_dataset",
    "load_experiment",
    "load_fpos_shap_importance",
    "load_leave_one_family_out_summary",
    "load_or_run_experiment",
    "load_raw_dataset",
    "load_recipe_result",
    "make_recording_key",
    "make_run_artifact_paths",
    "notebook_output_dirs",
    "plot_approach_comparison",
    "plot_benchmark_metric",
    "plot_domain_auc_annotated",
    "plot_domain_shift_separability",
    "plot_family_r2_heatmap",
    "plot_fpos_fmiss_ladder",
    "plot_fpos_shap_top",
    "plot_group_metric",
    "plot_label_budget",
    "plot_pca_projection",
    "plot_pca_projection_3d",
    "plot_prediction_scatter",
    "plot_target_asymmetry",
    "plot_top_feature_shift",
    "plot_waterfall_progression",
    "recording_disjoint_split",
    "run_experiment",
    "run_recipe",
    "save_figure",
    "save_table",
    "validate_recipe_registry",
    "validate_disjoint_recordings",
    "write_manifest",
]
