name: spike-qc-local
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ipykernel
  - jupyterlab=4.*
  - numpy=1.26.4
  - pandas=2.2.3
  - scipy=1.14.1
  - scikit-learn=1.5.2
  - pyarrow=18.1.0
  - matplotlib=3.9.*
  - seaborn=0.13.*
  - xgboost=2.1.*
  - tqdm
  - psutil
  - rich
  - pip:
      - spikeinterface==0.103.2
      - spikeforest==0.12.8
      - kachery-cloud
      - mtscomp
      - numcodecs==0.15.1
      - zarr==2.18.5
